### PR TITLE
Added navbar (#29)

### PR DESCRIPTION
**Pull request by SushantPatial**
Fixes: #29

Screenshots:

image

image

### CODE REVIEW

**Comment by SushantPatial** [comment]
Please review: https://memories-3fxq03hm5-shreya024.vercel.app/posts

**Comment by shreya024** [comment]
> Please review: https://memories-3fxq03hm5-shreya024.vercel.app/posts

Move the toggle menu icon to the extreme left.Everything else LGTM :)

**Review by Debdeep1 — APPROVED** [review]

**Comment by SushantPatial** [comment]
https://memories-eoq883zc7-shreya024.vercel.app/posts

image

image

**Review by shreya024 — APPROVED** [review]

**Comment by shreya024** [comment]
Great job @SushantPatial

**Pull request merged**
