### PR TITLE
Issue Number #7

### PR DESCRIPTION
**Pull request by AnshuMishra01**
This si the pull request for Issue number 7

### CODE REVIEW

**Comment by shreya024** [comment]
> This si the pull request for Issue number 7

Enhance the UI of the form according to the style of the loading page/footer and try to use a modal

**Review by soumali28 — CHANGES_REQUESTED** [review]
Untitled

- Add some margin in between the input box 
-  move the file input at the top and then start with text inputs
- give some margin between submit and clear button
- remove the black border or just decrease the width
- give a little bit padding to the form

**Comment by AnshuMishra01** [comment]
Screenshot 2022-08-05 234955

Its showing like this

**Comment by AnshuMishra01** [comment]
image
see

**Review by soumali28 — APPROVED** [review]

**Comment by soumali28** [comment]
@AnshuMishra01 Yep perfect commit the changes

**Review by soumali28 — CHANGES_REQUESTED** [review]
commit the changes

**Comment by AnshuMishra01** [comment]
Done

**Review by soumali28 — APPROVED** [review]

**Pull request merged**
