### PR TITLE
Add validation to Create Memory form

### PR DESCRIPTION
**Pull request by codingmickey**
✅ Added Basic form validation to throw error when one of the fields are empty

Issue: #12 
image

### CODE REVIEW

**Comment by shreya024** [comment]
> ✅ Added Basic form validation to throw error when one of the fields are empty
> 
> Issue: #12 image

validation should be to throw error when 
1.**all** of the fields are empty
2.Creator,Title or Message are just numbers
3.have suitable max word limit for the creator,title and message
4.file type chosen is not image or video(like docs or other file types)

**Comment by codingmickey** [comment]
Okay I'll update accordingly

**Review by soumali28 — CHANGES_REQUESTED** [review]
changes as told by @shreya024

**Review by soumali28 — APPROVED** [review]

**Comment by shreya024** [comment]
@codingmickey Any updates?

**Comment by soumali28** [comment]
@shreya024 he has made the changes and committed it

**Comment by codingmickey** [comment]
> @codingmickey Any updates?

I'll commit the changes by morning

**Review by soumali28 — CHANGES_REQUESTED** [review]
please resolve the conflicts. pull the changes and then push it.

**Review by soumali28 — APPROVED** [review]

**Pull request merged**
