### PR TITLE
Dark Mode Implementation #17 Added toggle button in footer and css for light theme

### PR DESCRIPTION
**Pull request by mridulpal019**
Screenshot (107)
Screenshot (108)

### CODE REVIEW

**Comment by shreya024** [comment]
@mridulpal019 change css of login and loading pages as well and give a different bg.png for the background in light theme

**Review by Debdeep1 — APPROVED** [review]

**Comment by mridulpal019** [comment]
@shreya024 made the said changes.

**Comment by shreya024** [comment]
> @shreya024 done the said changes.

LGTM! add the change theme button in those two pages as well

**Comment by mridulpal019** [comment]
> > @shreya024 done the said changes.
> 
> LGTM! add the change theme button in those two pages as well

@sherya024 where should I place the button in login page.... in the upper part?

**Comment by shreya024** [comment]
> > > @shreya024 done the said changes.
> > 
> > 
> > LGTM! add the change theme button in those two pages as well
> 
> @shreya024 where should I place the button in login page.... in the upper part?

Sure in the top right corner

**Review by Susmita-Dey — APPROVED** [review]
LGTM

**Pull request merged**
