### PR TITLE
User Profile Page

### PR DESCRIPTION
**Pull request by nobel10122025**
I have created a User Profile Page

### CODE REVIEW

**Review by SMD-1 — APPROVED** [review]
looks lgtm

**Comment by shreya024** [comment]
> looks lgtm

@SMD-1 Kindly help @nobel10122025 remove the merge conflicts

**Comment by nobel10122025** [comment]
please can someone help me in resolving this merge conflict.  because i have tried pulling and again pushing. 
but still it didnt work so provide me some suggestions

**Comment by shreya024** [comment]
> please can someone help me in resolving this merge conflict. because i have tried pulling and again pushing. but still it didnt work so provide me some suggestions

Try running npm install

**Comment by nobel10122025** [comment]
i have tried that as well but it didn't work.

**Comment by nobel10122025** [comment]
I am sorry for wasting all of your time. i am giving up . please assign this to someone else. i wasnt able to resolve it .
i am sorry again . and please close this PR as well. thank you for this great experience.

**Comment by soumali28** [comment]
@nobel10122025 hey dont be so sad it will solve pull the changes first in you local machine do npm install and then push it check if its working on the localhost before pushing it

**Review by SMD-1 — APPROVED** [review]

**Pull request closed without merging**
