### PR TITLE
User profile page

### PR DESCRIPTION
**Pull request by nobel10122025**
1 . Created a User Profile Page
2 . Created a readme for client folder

### CODE REVIEW

**Comment by shreya024** [comment]
@nobel10122025 Resolve the conflicts

**Comment by nobel10122025** [comment]
> @nobel10122025 Resolve the conflicts

can you please help me by saying does this issue still persist or should i create a new PR with my main branch 
this is my first contribution so i am not getting why this conflict has araised. Sorry

**Comment by soumali28** [comment]
@nobel10122025 just pull the changes before you push it the conflicts will be resolved

**Comment by nobel10122025** [comment]
@soumali28 i guess i have already done that. But how to check if the conflict still exist!

**Comment by soumali28** [comment]
see in the bottom where the git symbol is it showing the branch has conflicts and also shows the conflicting files

**Comment by nobel10122025** [comment]
i think it doesn't have any conflicts now 
image

@soumali28 please let me know if this is fine or ?

**Comment by soumali28** [comment]
not in the vs code I meant in github in the pr right here
Screenshot 2022-08-14 182640

**Comment by nobel10122025** [comment]
@soumali28 can i create a new PR ? i dont know what to do now. i have tried things but that message is not changing:((

**Comment by soumali28** [comment]
Ok close this pr and make a new one and before pushing  the code make sure to pull it.

**Comment by nobel10122025** [comment]
I am closing this PR because i am not able to Resolve this Conflict.  Will create a new one from the master branch.

**Pull request closed without merging**
