### PR TITLE
Implemented User model

### PR DESCRIPTION
**Pull request by codingmickey**
Regarding #41 are there any more fields required?

### CODE REVIEW

**Review by Debdeep1 — APPROVED** [review]

**Comment by Debdeep1** [comment]
> Regarding #41 are there any more fields required?

All these updates are working fine on your localhost?

**Review by Susmita-Dey — APPROVED** [review]
LGTM.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Review by soumali28 — APPROVED** [review]

**Comment by shreya024** [comment]
@codingmickey Add the new fields so I can merge the PR

**Comment by codingmickey** [comment]
@shreya024 How does this look now? sorry for such a delayed message as was very busy in some college procedures

**Comment by shreya024** [comment]
> @shreya024 How does this look now? sorry for such a delayed reply as was very busy in some college procedures

No problem. Under review now

**Review by Debdeep1 — APPROVED** [review]

**Review by soumali28 — APPROVED** [review]

**Review by Susmita-Dey — APPROVED** [review]
LGTM

**Pull request merged**
