### PR TITLE
Implemented Login/Sign Up page

### PR DESCRIPTION
**Pull request by KARTIK-RAINA5802**

### CODE REVIEW

**Comment by KARTIK-RAINA5802** [comment]
Ok, I found out that there were some errors due to which deployment failed and I solved those errors and it's working fine now on my system but GitGuardian is giving some errors related to MongoDB credentials which I am not able to solve. Can anyone please help with this issue?

And yes I have resolved merge conflicts and did npm I also before pushing.

**Comment by shreya024** [comment]
> Ok, I found out that there were some errors due to which deployment failed and I solved those errors and it's working fine now on my system but GitGuardian is giving some errors related to MongoDB credentials which I am not able to solve. Can anyone please help with this issue?
> 
> And yes I have resolved merge conflicts and did npm I also before pushing.

Great work on resolving the merge conflicts.Don't worry about the MongoDB credentials thing but the client side deployment is failing.
image

**Comment by KARTIK-RAINA5802** [comment]
Yes I worked on that issue and solved the errors and it started working. So may I push the changes and create a new PR ?

**Comment by shreya024** [comment]
> Yes I worked on that issue and solved the errors and it started working. So may I push the changes and create a new PR ?

Just push the changes,it'll reflect here only.No need to make a new PR

**Comment by KARTIK-RAINA5802** [comment]
Can you send me vercel error because I am not able to see any error on my local system and it's working fine.  
I also connected it to my MongoDB compass to check whether login/signup is working or not and it was working.

Screenshot (1381)

**Comment by KARTIK-RAINA5802** [comment]
and I also tried to check the vercel details but it's showing 404 page not found.

**Comment by shreya024** [comment]
> and I also tried to check the vercel details but it's showing 404 page not found.

This is the vercel error
image

**Comment by KARTIK-RAINA5802** [comment]
Can anyone help me with this issue? I am not able to find out errors locally which is making it more difficult for me to figure out what's going wrong.

And earlier I closed my PR which passed the two checks and then I just pulled the changes and created this new PR and it's not able to pass client-side deployment. I don't know what happened.

**Comment by shreya024** [comment]
> Can anyone help me with this issue? I am not able to find out errors locally which is making it more difficult for me to figure out what's going wrong.
> 
> And earlier I closed my PR which passed the two checks and then I just pulled the changes and created this new PR and it's not able to pass client-side deployment. I don't know what happened.

You can tag the Project Mentors and fellow contributors in discord for help.You could also try deploying your branch on your vercel to figure out the error :)

**Comment by prakhar728** [comment]
> Can anyone help me with this issue? I am not able to find out errors locally which is making it more difficult for me to figure out what's going wrong.
> 
> And earlier I closed my PR which passed the two checks and then I just pulled the changes and created this new PR and it's not able to pass client-side deployment. I don't know what happened.

Okay I am not sure. But did you add **.env** file and Environment variables on the frontend? With React you need to name the variables as *REACT_APP_YOUR_VARIABLE*

**Comment by KARTIK-RAINA5802** [comment]
I am getting this error. What should I do now ? 

image

**Comment by KARTIK-RAINA5802** [comment]
I guess It is build successfully right ?

image

**Comment by KARTIK-RAINA5802** [comment]
And I am also getting merge conflicts should I resolve them first?

**Comment by shreya024** [comment]
> And I am also getting merge conflicts should I resolve them first?

Yes

**Comment by shreya024** [comment]
@KARTIK-RAINA5802 Resolve the conflicts and complete the deployment fast so we can merge.Else this issue will be up for reassignment

**Comment by soumali28** [comment]
@KARTIK-RAINA5802 any updates?? please resolve the conflicts so that we can merge the pr

**Comment by KARTIK-RAINA5802** [comment]
I actually did cleared the merge conflicts but there are still many errors
coming and I am not able to solve them because I have just started react
and also not getting the the time due to exams and college work.

But I really tried my best to implement this functionality but it
didn't work out. This was my first open source experience and I did learned
a lot from it but  I feel sad as I couldn't contribute.

Thank you for giving me a chance to participate and sorry as I couldn't
complete it.

Please unassign me from this issue.

**Comment by fykaa** [comment]
Thanks a lot for your contributions @KARTIK-RAINA5802 . We are happy that you tried. Unassigning you for now, you could still work on this issue later, All the best!

**Pull request closed without merging**
