### PR TITLE
Fix Issue: #46 Posts UI improvement 

### PR DESCRIPTION
**Pull request by SahilDahekar**
- Made the post cards Responsive.
- Added glassmorphism to the posts cards.
- Added animation on load to the cards.

### CODE REVIEW

**Comment by shreya024** [comment]
> * Made the post cards Responsive.
> * Added glassmorphism to the posts cards.
> * Added animation on load to the cards.

@SahilDahekar Great! Add some ss or gif of the same

**Review by Susmita-Dey — APPROVED** [review]
LGTM. Good job.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Comment by SahilDahekar** [comment]
Here are some screen shots and a video of the same

- Previously the cards were collapsing. 

Screenshot 2022-09-10 132640

- After improving the responsiveness it looks like this
Screenshot 2022-09-10 132601
Here is the video for transition of cards loading from above its quite small detail but looks good.
[Memories-App.webm](https://user-images.githubusercontent.com/97726887/189474700-10043f99-f98d-4ed3-8a3f-31198044f527.webm)

**Comment by SahilDahekar** [comment]
@shreya024  @Debdeep1 Also i have a doubt regarding this PR i made has 46 commits i dont know why i just made 4 commit for my changes to the post.
So should i create a new PR for let this be

**Comment by shreya024** [comment]
> @shreya024 @Debdeep1 Also i have a doubt regarding this PR i made has 43 commits i dont know why i just made 4 commit for my changes to the post. So should i create a new PR for let this be

I think it's because u r trying to merge into main.Please make a new PR to the SSOC branch.Everything else LGTM!

**Pull request closed without merging**
